REAL_NODES = [
    "Akutmottagning Sahlgrenska",
    "Röntgen Sahlgrenska",
    "IVA Sahlgrenska",
    "Operation Sahlgrenska",
    "Thoraxoperation",
    "Thoraxintensiven",
    "Neurologi Sahlgrenska",
    "Vårdavdelning Sahlgrenska",
    "Ortopedi Sahlgrenska",
    "Kirurgi Sahlgrenska",
    "Hjärtavdelning",
    "Onkologi Sahlgrenska",
    "Barnakuten",
    "Barnoperation",
    "Barnintensiven",
    "Klinisk fysiologi",
    "Medicinsk genetik",
    "Nuklearmedicin",
    "Infektionsklinik",
    "Rehabilitering Sahlgrenska",
    "Hudkliniken",
    "Ögonmottagning",
    "ÖNH Sahlgrenska",
    "Gastroenterologi",
    "Lungmottagning",
    "Transplantation",
    "Geriatrik Sahlgrenska",
    "Barnröntgen",
    "Barnneurologi",
    "Barnhjärta",
    "Endokrinologi",
    "Gynekologi Sahlgrenska",
    "Barnintensiven",
    "Barnakutmottagning",
    "Barnmottagning",
    "Barnkirurgi",
    "Barnläkemedel",
    "Barninfektion",
    "Barnröntgen MRI",
    "Förlossning",
    "Ultraljudscentral",
    "Logopedi",
    "Psykiatri",
    "Smärtenhet",
    "Kardiologi",
    "Urologi",
    "Nefrologi",
    "Gastrocentrum",
    "Infektionsmottagning",
    "Akutintag",
    "Blodcentral",
    "Centralkök",
    "Klinisk kemi",
    "Klinisk patologi",
    "Klinisk mikrobiologi",
    "Intensivvårdsavdelning 2",
    "Intensivvårdsavdelning 3",
    "Thoraxröntgen",
    "Barnonkologi",
    "Barnkardiologi",
    "Barnallergi",
    "Barnhematologi",
    "Barnögon",
    "Barnlogopedi",
    "Barnpsykologi",
    "Barnhud",
    "Barnsmärta",
    "Barnakutkirurgi",
    "Barnläkarteam",
    "Barnkoordinator",
    "Barnanestesi",
    "Barnambulans",
    "Barnpalliativ",
    "Barnavdelning 1",
    "Barnavdelning 2",
    "Barnavdelning 3",
    "Barnavdelning 4",
    "Barnavdelning 5",
    "Barnavdelning 6",
    "Barnavdelning 7",
    "Barnavdelning 8",
    "Barnavdelning 9",
    "Barnavdelning 10",
    "Barnsjukhusets kök",
    "Barnsjukhusets lekterapi",
    "Barnsjukhusets administration",
    "Barnsjukhusets IT-support",
    "Barnsjukhusets forskning",
    "Barnsjukhusets bibliotek",
    "Barnsjukhusets konferens",
    "Barnsjukhusets vaktmästeri",
    "Barnsjukhusets säkerhet",
    "Barnsjukhusets förråd",
    "Barnsjukhusets ekonomi",
    "Barnsjukhusets HR",
    "Barnsjukhusets reception",
    "Barnsjukhusets parkering",
    "Barnsjukhusets ingång A",
    "Barnsjukhusets ingång B"
]
